// Much of the format validation code in this file was generated by AI.
// I'm not ashamed; you're ashamed.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using NUnit.Framework;
using TestHelpers;

namespace Json.Schema.Tests.Suite;

public class ValidationOptimized
{
	private const string _testCasesPath = @"../../../../../ref-repos/JSON-Schema-Test-Suite/tests";
	private const string _remoteSchemasPath = @"../../../../../ref-repos/JSON-Schema-Test-Suite/remotes";

	private const bool _useExternal = false;
	private const bool _runDraftNext = false;
	private const string _externalTestCasesPath = @"../../../../../../JSON-Schema-Test-Suite/tests";
	private const string _externalRemoteSchemasPath = @"../../../../../../JSON-Schema-Test-Suite/remotes";

	// Tests to explicitly ignore: [fileName, collectionDescription, testCaseDescription ("*" for all)]
	private static readonly HashSet<(string, string, string)> _ignoredTests =
	[
		("idn-email", "validation of an internationalized e-mail addresses", "a local part with a lone UTF-16 surrogate is invalid"),
		("hostname", "validation of A-label (punycode) host names", "a valid host name (example.test in Hangul)"),
		("hostname", "validation of A-label (punycode) host names", "Arabic-Indic digits not mixed with Extended Arabic-Indic digits"),
		("hostname", "validation of A-label (punycode) host names", "Exceptions that are PVALID, left-to-right chars"),
		("hostname", "validation of A-label (punycode) host names", "Exceptions that are PVALID, right-to-left chars"),
		("hostname", "validation of A-label (punycode) host names", "Extended Arabic-Indic digits not mixed with Arabic-Indic digits"),
		("hostname", "validation of A-label (punycode) host names", "Greek KERAIA followed by Greek"),
		("hostname", "validation of A-label (punycode) host names", "Hebrew GERESH preceded by Hebrew"),
		("hostname", "validation of A-label (punycode) host names", "Hebrew GERSHAYIM preceded by Hebrew"),
		("hostname", "validation of A-label (punycode) host names", "KATAKANA MIDDLE DOT with Han"),
		("hostname", "validation of A-label (punycode) host names", "KATAKANA MIDDLE DOT with Hiragana"),
		("hostname", "validation of A-label (punycode) host names", "KATAKANA MIDDLE DOT with Katakana"),
		("hostname", "validation of A-label (punycode) host names", "MIDDLE DOT with surrounding 'l's"),
		("hostname", "validation of A-label (punycode) host names", "ZERO WIDTH JOINER preceded by Virama"),
		("hostname", "validation of A-label (punycode) host names", "ZERO WIDTH NON-JOINER not preceded by Virama but matches regexp"),
		("hostname", "validation of A-label (punycode) host names", "ZERO WIDTH NON-JOINER preceded by Virama"),
		("idn-hostname", "validation of internationalized host names", "a name longer than 253 characters is invalid"),
		("idn-hostname", "validation of internationalized host names", "a U-label whose A-label form is longer than 63 octets is invalid"),
		("idn-hostname", "validation of internationalized host names", "Bidi domain name with a digit-first label is invalid"),
		("idn-hostname", "validation of internationalized host names", "contains illegal char U+302E Hangul single dot tone mark"),
		("idn-hostname", "validation of internationalized host names", "Exceptions that are DISALLOWED, left-to-right chars"),
		("idn-hostname", "validation of internationalized host names", "Exceptions that are DISALLOWED, right-to-left chars"),
		("idn-hostname", "validation of internationalized host names", "KATAKANA MIDDLE DOT with no Hiragana, Katakana, or Han"),
		("idn-hostname", "validation of internationalized host names", "KATAKANA MIDDLE DOT with no other characters"),
		("idn-hostname", "validation of internationalized host names", "label starting with a digit before a right-to-left letter is invalid"),
		("idn-hostname", "validation of internationalized host names", "left-to-right label containing a right-to-left letter is invalid"),
		("idn-hostname", "validation of internationalized host names", "right-to-left label mixing both digit types is invalid"),
		("idn-hostname", "validation of internationalized host names", "valid Chinese Punycode"),
		("idn-hostname", "validation of internationalized host names", "zero width non-joiner must pass at every occurrence"),
		("idn-hostname", "validation of separators in internationalized host names", "fullwidth full stop as label separator"),
		("idn-hostname", "validation of separators in internationalized host names", "halfwidth ideographic full stop as label separator"),
		("idn-hostname", "validation of separators in internationalized host names", "ideographic full stop as label separator"),
		("idn-hostname", "validation of separators in internationalized host names", "label too long if separator ignored (fullwidth full stop)"),
		("idn-hostname", "validation of separators in internationalized host names", "label too long if separator ignored (halfwidth ideographic full stop)"),
		("idn-hostname", "validation of separators in internationalized host names", "label too long if separator ignored (ideographic full stop)"),
	];

	public static IEnumerable<TestCaseData> TestCases()
	{
		return GetTests("draft6")
			.Concat(GetTests("draft7"))
			.Concat(GetTests("draft2019-09"))
			.Concat(GetTests("draft2020-12"))
			.Concat(_runDraftNext ? GetTests("v1") : []);
	}

	private static IEnumerable<TestCaseData> GetTests(string draftFolder)
	{
		// ReSharper disable once HeuristicUnreachableCode
		var testCasesPath = _useExternal ? _externalTestCasesPath : _testCasesPath;

		var testsPath = Path.Combine(TestContext.CurrentContext.WorkDirectory, testCasesPath, $"{draftFolder}/")
			.AdjustForPlatform();
		if (!Directory.Exists(testsPath)) return [];

		var fileNames = Directory.GetFiles(testsPath, "*.json", SearchOption.AllDirectories);
		var evaluationOptions = new EvaluationOptions
		{
			OutputFormat = OutputFormat.Flag,
		};

		var allTests = new List<TestCaseData>();
		foreach (var fileName in fileNames)
		{
			var shortFileName = Path.GetFileNameWithoutExtension(fileName);

			// adjust for format
			evaluationOptions.RequireFormatValidation = fileName.Contains("format/".AdjustForPlatform());

			var contents = File.ReadAllText(fileName);
			var collections = JsonSerializer.Deserialize<List<TestCollection>>(contents, TestEnvironment.TestSuiteSerializationOptions);

			foreach (var collection in collections!)
			{
				collection.IsOptional = fileName.Contains("optional");

				foreach (var test in collection.Tests)
				{
					var dialect = draftFolder switch
					{
						"draft6" => Dialect.Draft06,
						"draft7" => Dialect.Draft07,
						"draft2019-09" => Dialect.Draft201909,
						"draft2020-12" => Dialect.Draft202012,
						"v1" => Dialect.V1,
						_ => throw new ArgumentOutOfRangeException(nameof(draftFolder), $"{draftFolder} is unsupported")
					};

					var buildOptions = new BuildOptions
					{
						Dialect = dialect,
						SchemaRegistry = new()
					};
					if (_ignoredTests.Contains((shortFileName, collection.Description, test.Description))) continue;
					if (_ignoredTests.Contains((shortFileName, collection.Description, "*"))) continue;

					var optional = collection.IsOptional ? "(optional) / " : null;
					var name = $"{draftFolder} / {optional}{shortFileName} / {collection.Description} / {test.Description}";
					var evaluationOptionsCopy = EvaluationOptions.From(evaluationOptions);
					allTests.Add(new TestCaseData(collection, test, shortFileName, buildOptions, evaluationOptionsCopy) { TestName = name });
				}
			}
		}

		return allTests;
	}

	[OneTimeSetUp]
	public void LoadRemoteSchemas()
	{
		// ReSharper disable once HeuristicUnreachableCode
		var remotesPath = Path.Combine(TestContext.CurrentContext.WorkDirectory, _useExternal ? _externalRemoteSchemasPath : _remoteSchemasPath)
			.AdjustForPlatform();
		if (!Directory.Exists(remotesPath)) throw new Exception("Cannot find remotes folder");

		var fileNames = Directory.GetFiles(remotesPath, "*.json", SearchOption.AllDirectories);

		foreach (var fileName in fileNames)
		{
			try
			{
				Dialect? dialect;
				if (fileName.Contains("draft6"))
					dialect = Dialect.Draft06;
				else if (fileName.Contains("draft7"))
					dialect = Dialect.Draft07;
				else if (fileName.Contains("draft2019-09"))
					dialect = Dialect.Draft201909;
				else if (fileName.Contains("draft2020-12"))
					dialect = Dialect.Draft202012;
				else
					dialect = Dialect.V1;

				var buildOptions = new BuildOptions
				{
					Dialect = dialect
				};
				var uri = new Uri(fileName.Replace(remotesPath, "http://localhost:1234").Replace('\\', '/'));
				if (SchemaRegistry.Global.Get(uri) != null) return; // may have been loaded from other test if running all together

				var schema = JsonSchema.FromFile(fileName, buildOptions, uri);
				SchemaRegistry.Global.Register(uri, schema); // it seems a number of remotes have `$id`s different from their file path
			}
			catch (JsonSchemaException e)
			{
				TestConsole.WriteLine($"Error loading file '{fileName}': {e}");
			}
		}
	}

	[TestCaseSource(nameof(TestCases))]
	public void Test(TestCollection collection, TestCase test, string fileName, BuildOptions buildOptions, EvaluationOptions evaluationOptions)
	{
		TestConsole.WriteLine();
		TestConsole.WriteLine();
		TestConsole.WriteLine(fileName);
		TestConsole.WriteLine(collection.Description);
		TestConsole.WriteLine(test.Description);
		TestConsole.WriteLine(test.Valid ? "valid" : "invalid");
		TestConsole.WriteLine();
		TestConsole.WriteLine(JsonSerializer.Serialize(collection.Schema, TestEnvironment.TestOutputSerializerOptions));
		TestConsole.WriteLine();
		TestConsole.WriteLine(JsonSerializer.Serialize(test.Data, TestEnvironment.TestOutputSerializerOptions));
		TestConsole.WriteLine();

		JsonSchema schema;
		try
		{
			schema = Measure.Run("Build", () => JsonSchema.Build(collection.Schema, buildOptions));
		}
		catch (Exception e)
		{
			Console.WriteLine(e);
			if (collection.IsOptional)
			{
				Assert.Inconclusive();
				return;
			}

			throw;
		}

		EvaluationResults result;
		try
		{
			result = Measure.Run("Evaluate", () => schema.Evaluate(test.Data, evaluationOptions));
		}
		catch (Exception e)
		{
			Console.WriteLine(e);
			if (collection.IsOptional)
			{
				Assert.Inconclusive();
				return;
			}

			throw;
		}

		//result.ToBasic();
		TestConsole.WriteLine();
		TestConsole.WriteLine("Result:");
		TestConsole.WriteLine(JsonSerializer.Serialize(result, TestEnvironment.TestOutputSerializerOptions));

		if (collection.IsOptional && result.IsValid != test.Valid)
			Assert.Inconclusive("Test optional");
		Assert.That(result.IsValid, Is.EqualTo(test.Valid));
	}

	[Test]
	public void EnsureTestSuiteConfiguredForServerBuild()
	{
		Assert.That(_useExternal, Is.False);
		//Assert.IsFalse(_runDraftNext);
	}
}